
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DevBuild_Assessment6_PutMeOnTheList.Models
{

using System;
    using System.Collections.Generic;
    
public partial class GoTCharacter
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public GoTCharacter()
    {

        this.Guests = new HashSet<Guest>();

    }


    public int CharacterId { get; set; }

    public string Name { get; set; }

    public string House { get; set; }

    public string Allegiance { get; set; }

    public string Book { get; set; }

    public string Alias { get; set; }

    public int ApiId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Guest> Guests { get; set; }

}

}
