
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DevBuild_Assessment6_PutMeOnTheList.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Guest
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Guest()
    {

        this.Dishes = new HashSet<Dish>();

    }


    public int GuestID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public Nullable<System.DateTime> AttendanceDate { get; set; }

    public string EmailAddress { get; set; }

    public string Guest1 { get; set; }

    public Nullable<int> CharacterId { get; set; }

    public string CharacterName { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Dish> Dishes { get; set; }

    public virtual GoTCharacter GoTCharacter { get; set; }

}

}
